version: '3.7'

secrets:
  fitness_app-MONGO_ROOT_PASSWORD:
    file: ./MONGO_ROOT_PASSWORD.txt

networks:
  public:
    driver: overlay
    driver_opts: 
      encrypted: 'true'
    attachable: true

volumes:
  mongo-data: 

services:
  fitnesswebapi:
    image: ${DOCKER_REGISTRY-}fitnesswebapi
    depends_on:
      - mongo
    networks:
      - public
    build:
      context: .
      dockerfile: FitnessWebApi/Dockerfile
    env_file:
      - ./MONGO_CONNECTION_STRING.txt
  mongo:
    image: mongo
    container_name: mongo-db
    hostname: mongo-db
    restart: always
    networks: 
      - public
    ports:
        - '27017:27017'
    volumes:
      - mongo-data:/var/lib/mongo/data
    secrets:
      - source: fitness_app-MONGO_ROOT_PASSWORD
        target: MONGO_ROOT_PASSWORD
        uid: '999'
        gid: '999'
        mode: 0400

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_ROOT_PASSWORD
    labels: 
      - mongo-db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    networks: 
      - public
    depends_on: 
        - mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo12345
